version: '3.8'

services:
  mysql-test:
    image: mysql:8.0
    container_name: mysql-task_list
    restart: always
    environment:
      MYSQL_DATABASE: task_list_service
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    networks:
      - backend
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:
    driver: local

networks:
  backend:
    driver: bridge
