server:
  port: 8080

spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enable: true
  jpa:
    hibernate:
      ddl-auto: create

logging:
  level:
    root: DEBUG